/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BusBooking;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.print.PrinterException;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTML;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author uadar
 */
public class BusBooking extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form BusBooking
     */
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    int seat = 0;
    public BusBooking() {
        initComponents();
        connect();
        btn1.addMouseListener(this);
        btn2.addMouseListener(this);
        btn3.addMouseListener(this);
        btn4.addMouseListener(this);
        btn5.addMouseListener(this);
        btn6.addMouseListener(this);
        btn7.addMouseListener(this);
        btn8.addMouseListener(this);
        btn9.addMouseListener(this);
        btn10.addMouseListener(this);
        btn11.addMouseListener(this);
        btn12.addMouseListener(this);
        btn13.addMouseListener(this);
        btn14.addMouseListener(this);
        btn15.addMouseListener(this);
        btn16.addMouseListener(this);
        btn17.addMouseListener(this);
        btn18.addMouseListener(this);
        btn19.addMouseListener(this);
        btn20.addMouseListener(this);
        btn21.addMouseListener(this);
        btn22.addMouseListener(this);
        btn23.addMouseListener(this);
        btn24.addMouseListener(this);
        btn25.addMouseListener(this);
        btn26.addMouseListener(this);
        btn27.addMouseListener(this);
        btn28.addMouseListener(this);
        btn29.addMouseListener(this);
        btn30.addMouseListener(this);
        
        //Date date = new Date();
//        txtDate.setMinSelectableDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void connect()
    {
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/busBooking", "root", "");	
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel1.setText("Bus Booking System");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel2.setText("Choose Date");

        txtDate.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDatePropertyChange(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose Your Seat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 36))); // NOI18N

        btn1.setBackground(new java.awt.Color(102, 255, 204));
        btn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn1.setText("1");
        btn1.setMaximumSize(new java.awt.Dimension(70, 35));
        btn1.setMinimumSize(new java.awt.Dimension(70, 35));
        btn1.setPreferredSize(new java.awt.Dimension(70, 35));

        btn5.setBackground(new java.awt.Color(102, 255, 204));
        btn5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn5.setText("5");
        btn5.setMaximumSize(new java.awt.Dimension(70, 35));
        btn5.setMinimumSize(new java.awt.Dimension(70, 35));
        btn5.setPreferredSize(new java.awt.Dimension(70, 35));

        btn3.setBackground(new java.awt.Color(102, 255, 204));
        btn3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn3.setText("3");
        btn3.setMaximumSize(new java.awt.Dimension(70, 35));
        btn3.setMinimumSize(new java.awt.Dimension(70, 35));
        btn3.setPreferredSize(new java.awt.Dimension(70, 35));

        btn4.setBackground(new java.awt.Color(102, 255, 204));
        btn4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn4.setText("4");
        btn4.setMaximumSize(new java.awt.Dimension(70, 35));
        btn4.setMinimumSize(new java.awt.Dimension(70, 35));
        btn4.setPreferredSize(new java.awt.Dimension(70, 35));

        btn2.setBackground(new java.awt.Color(102, 255, 204));
        btn2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn2.setText("2");
        btn2.setMaximumSize(new java.awt.Dimension(70, 35));
        btn2.setMinimumSize(new java.awt.Dimension(70, 35));
        btn2.setPreferredSize(new java.awt.Dimension(70, 35));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(102, 255, 204));
        btn6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn6.setText("6");
        btn6.setMaximumSize(new java.awt.Dimension(70, 35));
        btn6.setMinimumSize(new java.awt.Dimension(70, 35));
        btn6.setPreferredSize(new java.awt.Dimension(70, 35));

        btn7.setBackground(new java.awt.Color(102, 255, 204));
        btn7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn7.setText("7");
        btn7.setMaximumSize(new java.awt.Dimension(70, 35));
        btn7.setMinimumSize(new java.awt.Dimension(70, 35));
        btn7.setPreferredSize(new java.awt.Dimension(70, 35));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(102, 255, 204));
        btn8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn8.setText("8");
        btn8.setMaximumSize(new java.awt.Dimension(70, 35));
        btn8.setMinimumSize(new java.awt.Dimension(70, 35));
        btn8.setPreferredSize(new java.awt.Dimension(70, 35));

        btn9.setBackground(new java.awt.Color(102, 255, 204));
        btn9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn9.setText("9");
        btn9.setMaximumSize(new java.awt.Dimension(70, 35));
        btn9.setMinimumSize(new java.awt.Dimension(70, 35));
        btn9.setPreferredSize(new java.awt.Dimension(70, 35));

        btn10.setBackground(new java.awt.Color(102, 255, 204));
        btn10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn10.setText("10");
        btn10.setMaximumSize(new java.awt.Dimension(70, 35));
        btn10.setMinimumSize(new java.awt.Dimension(70, 35));
        btn10.setPreferredSize(new java.awt.Dimension(70, 35));

        btn11.setBackground(new java.awt.Color(102, 255, 204));
        btn11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn11.setText("11");
        btn11.setMaximumSize(new java.awt.Dimension(70, 35));
        btn11.setMinimumSize(new java.awt.Dimension(70, 35));
        btn11.setPreferredSize(new java.awt.Dimension(70, 35));

        btn12.setBackground(new java.awt.Color(102, 255, 204));
        btn12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn12.setText("12");
        btn12.setMaximumSize(new java.awt.Dimension(70, 35));
        btn12.setMinimumSize(new java.awt.Dimension(70, 35));
        btn12.setPreferredSize(new java.awt.Dimension(70, 35));
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn13.setBackground(new java.awt.Color(102, 255, 204));
        btn13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn13.setText("13");
        btn13.setMaximumSize(new java.awt.Dimension(70, 35));
        btn13.setMinimumSize(new java.awt.Dimension(70, 35));
        btn13.setPreferredSize(new java.awt.Dimension(70, 35));

        btn14.setBackground(new java.awt.Color(102, 255, 204));
        btn14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn14.setText("14");
        btn14.setMaximumSize(new java.awt.Dimension(70, 35));
        btn14.setMinimumSize(new java.awt.Dimension(70, 35));
        btn14.setPreferredSize(new java.awt.Dimension(70, 35));

        btn15.setBackground(new java.awt.Color(102, 255, 204));
        btn15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn15.setText("15");
        btn15.setMaximumSize(new java.awt.Dimension(70, 35));
        btn15.setMinimumSize(new java.awt.Dimension(70, 35));
        btn15.setPreferredSize(new java.awt.Dimension(70, 35));
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });

        btn16.setBackground(new java.awt.Color(102, 255, 204));
        btn16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn16.setText("16");
        btn16.setMaximumSize(new java.awt.Dimension(70, 35));
        btn16.setMinimumSize(new java.awt.Dimension(70, 35));
        btn16.setPreferredSize(new java.awt.Dimension(70, 35));

        btn17.setBackground(new java.awt.Color(102, 255, 204));
        btn17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn17.setText("17");
        btn17.setMaximumSize(new java.awt.Dimension(70, 35));
        btn17.setMinimumSize(new java.awt.Dimension(70, 35));
        btn17.setPreferredSize(new java.awt.Dimension(70, 35));
        btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn17ActionPerformed(evt);
            }
        });

        btn18.setBackground(new java.awt.Color(102, 255, 204));
        btn18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn18.setText("18");
        btn18.setMaximumSize(new java.awt.Dimension(70, 35));
        btn18.setMinimumSize(new java.awt.Dimension(70, 35));
        btn18.setPreferredSize(new java.awt.Dimension(70, 35));

        btn19.setBackground(new java.awt.Color(102, 255, 204));
        btn19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn19.setText("19");
        btn19.setMaximumSize(new java.awt.Dimension(70, 35));
        btn19.setMinimumSize(new java.awt.Dimension(70, 35));
        btn19.setPreferredSize(new java.awt.Dimension(70, 35));

        btn20.setBackground(new java.awt.Color(102, 255, 204));
        btn20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn20.setText("20");
        btn20.setMaximumSize(new java.awt.Dimension(70, 35));
        btn20.setMinimumSize(new java.awt.Dimension(70, 35));
        btn20.setPreferredSize(new java.awt.Dimension(70, 35));
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        btn21.setBackground(new java.awt.Color(102, 255, 204));
        btn21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn21.setText("21");
        btn21.setMaximumSize(new java.awt.Dimension(70, 35));
        btn21.setMinimumSize(new java.awt.Dimension(70, 35));
        btn21.setPreferredSize(new java.awt.Dimension(70, 35));

        btn22.setBackground(new java.awt.Color(102, 255, 204));
        btn22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn22.setText("22");
        btn22.setMaximumSize(new java.awt.Dimension(70, 35));
        btn22.setMinimumSize(new java.awt.Dimension(70, 35));
        btn22.setPreferredSize(new java.awt.Dimension(70, 35));
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });

        btn23.setBackground(new java.awt.Color(102, 255, 204));
        btn23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn23.setText("23");
        btn23.setMaximumSize(new java.awt.Dimension(70, 35));
        btn23.setMinimumSize(new java.awt.Dimension(70, 35));
        btn23.setPreferredSize(new java.awt.Dimension(70, 35));

        btn24.setBackground(new java.awt.Color(102, 255, 204));
        btn24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn24.setText("24");
        btn24.setMaximumSize(new java.awt.Dimension(70, 35));
        btn24.setMinimumSize(new java.awt.Dimension(70, 35));
        btn24.setPreferredSize(new java.awt.Dimension(70, 35));
        btn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24ActionPerformed(evt);
            }
        });

        btn25.setBackground(new java.awt.Color(102, 255, 204));
        btn25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn25.setText("25");
        btn25.setMaximumSize(new java.awt.Dimension(70, 35));
        btn25.setMinimumSize(new java.awt.Dimension(70, 35));
        btn25.setPreferredSize(new java.awt.Dimension(70, 35));

        btn26.setBackground(new java.awt.Color(102, 255, 204));
        btn26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn26.setText("26");
        btn26.setMaximumSize(new java.awt.Dimension(70, 35));
        btn26.setMinimumSize(new java.awt.Dimension(70, 35));
        btn26.setPreferredSize(new java.awt.Dimension(70, 35));

        btn27.setBackground(new java.awt.Color(102, 255, 204));
        btn27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn27.setText("27");
        btn27.setMaximumSize(new java.awt.Dimension(70, 35));
        btn27.setMinimumSize(new java.awt.Dimension(70, 35));
        btn27.setPreferredSize(new java.awt.Dimension(70, 35));
        btn27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn27ActionPerformed(evt);
            }
        });

        btn28.setBackground(new java.awt.Color(102, 255, 204));
        btn28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn28.setText("28");
        btn28.setMaximumSize(new java.awt.Dimension(70, 35));
        btn28.setMinimumSize(new java.awt.Dimension(70, 35));
        btn28.setPreferredSize(new java.awt.Dimension(70, 35));

        btn29.setBackground(new java.awt.Color(102, 255, 204));
        btn29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn29.setText("29");
        btn29.setMaximumSize(new java.awt.Dimension(70, 35));
        btn29.setMinimumSize(new java.awt.Dimension(70, 35));
        btn29.setPreferredSize(new java.awt.Dimension(70, 35));
        btn29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn29ActionPerformed(evt);
            }
        });

        btn30.setBackground(new java.awt.Color(102, 255, 204));
        btn30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn30.setText("30");
        btn30.setMaximumSize(new java.awt.Dimension(70, 35));
        btn30.setMinimumSize(new java.awt.Dimension(70, 35));
        btn30.setPreferredSize(new java.awt.Dimension(70, 35));
        btn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn25, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn26, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn30, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn28, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn29, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn27, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 36))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel4.setText("Name");

        txtName.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel5.setText("Amount");

        txtAmount.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        btnCheck.setBackground(new java.awt.Color(102, 255, 204));
        btnCheck.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnBook.setBackground(new java.awt.Color(102, 255, 204));
        btnBook.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(txtAmount)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bus Ticket", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 36))); // NOI18N

        txtBill.setColumns(20);
        txtBill.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtBill.setRows(5);
        jScrollPane1.setViewportView(txtBill);

        btnPrint.setBackground(new java.awt.Color(102, 255, 204));
        btnPrint.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        btnPrint.setText("Save Ticket");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
            .addComponent(btnPrint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn17ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn27ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn24ActionPerformed

    private void btn29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn29ActionPerformed

    private void btn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn30ActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            // TODO add your handling code here:
            txtBill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(BusBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        try{
            String name = txtName.getText();
            String price = txtAmount.getText();
            SimpleDateFormat dateForm = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateForm.format(txtDate.getDate());
            int seatNum = seat;
            String query = "Select * from ticketBooking where date = ? and seat = ?";
            pst = con.prepareStatement(query);
            pst.setString(1, date);
            pst.setInt(2, seatNum);
            rs = pst.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this, "This seat is already booked");
            }
            else
            {
		pst = con.prepareStatement("Insert into ticketBooking(name,price,seat,date) values (?,?,?,?)");
		pst.setString(1, name);
		pst.setString(2, price);
		pst.setInt(3, seatNum);
		pst.setString(4, date);
		int k = pst.executeUpdate();
		if(k==1)
		{
                    JOptionPane.showMessageDialog(this, "Booking Successfull");
			//bill();
		}
		else
		{
                    JOptionPane.showMessageDialog(this, "Something went wrong");	
		}
	}		
}
catch(Exception ex)
{
    System.out.println(ex);
}
        txtBill.setText("");
        int amount = 1000;
        txtBill.setText(txtBill.getText() + "**************************\n");
        txtBill.setText(txtBill.getText() + "*******TICKET DETAILS*****\n");
        txtBill.setText(txtBill.getText() + "**************************\n\n");
        txtBill.setText(txtBill.getText() + "\n\n");
        txtBill.setText(txtBill.getText() + "Name     :  " + txtName.getText() + "\n");
        txtBill.setText(txtBill.getText() + "Paid     :  " + txtAmount.getText() + "\n");
        txtBill.setText(txtBill.getText() + "Amount   :  " + amount + "\n");
        txtBill.setText(txtBill.getText() + "Balance  :  " + (Integer.parseInt(txtAmount.getText()) - amount) + "\n");
        txtBill.setText(txtBill.getText() + "Seats    :  " + seat + "\n\n");
        txtBill.setText(txtBill.getText() + "**************************\n");
        txtBill.setText(txtBill.getText() + "****THANKS FOR BOOKING****\n");
        txtBill.setText(txtBill.getText() + "**************************\n\n");
        

    }//GEN-LAST:event_btnBookActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        CheckAvailability ch = new CheckAvailability();
        ch.setVisible(true);
    }//GEN-LAST:event_btnCheckActionPerformed

    private void txtDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDatePropertyChange
        // TODO add your handling code here:
        connect();
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        btn10.setEnabled(true);
        btn11.setEnabled(true);
        btn12.setEnabled(true);
        btn13.setEnabled(true);
        btn14.setEnabled(true);
        btn15.setEnabled(true);
        btn16.setEnabled(true);
        btn17.setEnabled(true);
        btn18.setEnabled(true);
        btn19.setEnabled(true);
        btn20.setEnabled(true);
        btn21.setEnabled(true);
        btn22.setEnabled(true);
        btn23.setEnabled(true);
        btn24.setEnabled(true);
        btn25.setEnabled(true);
        btn26.setEnabled(true);
        btn27.setEnabled(true);
        btn28.setEnabled(true);
        btn29.setEnabled(true);
        btn30.setEnabled(true);
        try{
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            String dateForm = date.format(txtDate.getDate());
            pst = con.prepareStatement("Select * from ticketBooking where date = ?");
            pst.setString(1, dateForm);
            rs = pst.executeQuery();
            if(rs.next())
            {
		do{
                    if(rs.getString("seat").equals("1"))
			btn1.setEnabled(false);
                    else if(rs.getString("seat").equals("2"))
			btn2.setEnabled(false);
                    else if(rs.getString("seat").equals("3"))
			btn3.setEnabled(false);
                    else if(rs.getString("seat").equals("4"))
			btn4.setEnabled(false);
                    else if(rs.getString("seat").equals("5"))
			btn5.setEnabled(false);
                    else if(rs.getString("seat").equals("6"))
			btn6.setEnabled(false);
                    else if(rs.getString("seat").equals("7"))
			btn7.setEnabled(false);
                    else if(rs.getString("seat").equals("8"))
			btn8.setEnabled(false);
                    else if(rs.getString("seat").equals("9"))
			btn9.setEnabled(false);
                    else if(rs.getString("seat").equals("10"))
			btn10.setEnabled(false);
                    else if(rs.getString("seat").equals("11"))
			btn11.setEnabled(false);
                    else if(rs.getString("seat").equals("12"))
			btn12.setEnabled(false);
                    else if(rs.getString("seat").equals("13"))
			btn13.setEnabled(false);
                    else if(rs.getString("seat").equals("14"))
			btn14.setEnabled(false);
                    else if(rs.getString("seat").equals("15"))
			btn15.setEnabled(false);
                    else if(rs.getString("seat").equals("16"))
			btn16.setEnabled(false);
                    else if(rs.getString("seat").equals("17"))
			btn17.setEnabled(false);
                    else if(rs.getString("seat").equals("18"))
			btn18.setEnabled(false);
                    else if(rs.getString("seat").equals("19"))
			btn19.setEnabled(false);
                    else if(rs.getString("seat").equals("20"))
			btn20.setEnabled(false);
                    else if(rs.getString("seat").equals("21"))
			btn21.setEnabled(false);
                    else if(rs.getString("seat").equals("22"))
			btn22.setEnabled(false);
                    else if(rs.getString("seat").equals("23"))
			btn23.setEnabled(false);
                    else if(rs.getString("seat").equals("24"))
			btn24.setEnabled(false);
                    else if(rs.getString("seat").equals("25"))
			btn25.setEnabled(false);
                    else if(rs.getString("seat").equals("26"))
			btn26.setEnabled(false);
                    else if(rs.getString("seat").equals("27"))
			btn27.setEnabled(false);
                    else if(rs.getString("seat").equals("28"))
			btn28.setEnabled(false);
                    else if(rs.getString("seat").equals("29"))
			btn29.setEnabled(false);
                    else if(rs.getString("seat").equals("30"))
			btn30.setEnabled(false);
		}while(rs.next());
            }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_txtDatePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextArea txtBill;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        if(e.getSource() == btn1)
            seat = 1;
        if(e.getSource() == btn2)
            seat = 2;
        if(e.getSource() == btn3)
            seat = 3;
        if(e.getSource() == btn4)
            seat = 4;
        if(e.getSource() == btn5)
            seat = 5;
        if(e.getSource() == btn6)
            seat = 6;
        if(e.getSource() == btn7)
            seat = 7;
        if(e.getSource() == btn8)
            seat = 8;
        if(e.getSource() == btn9)
            seat = 9;
        if(e.getSource() == btn10)
            seat = 10;
        if(e.getSource() == btn11)
            seat = 11;
        if(e.getSource() == btn12)
            seat = 12;
        if(e.getSource() == btn13)
            seat = 13;
        if(e.getSource() == btn14)
            seat = 14;
        if(e.getSource() == btn15)
            seat = 15;
        if(e.getSource() == btn16)
            seat = 16;
        if(e.getSource() == btn17)
            seat = 17;
        if(e.getSource() == btn18)
            seat = 18;
        if(e.getSource() == btn19)
            seat = 19;
        if(e.getSource() == btn20)
            seat = 20;
        if(e.getSource() == btn21)
            seat = 21;
        if(e.getSource() == btn22)
            seat = 22;
        if(e.getSource() == btn23)
            seat = 23;
        if(e.getSource() == btn24)
            seat = 24;
        if(e.getSource() == btn25)
            seat = 25;
        if(e.getSource() == btn26)
            seat = 26;
        if(e.getSource() == btn27)
            seat = 27;
        if(e.getSource() == btn28)
            seat = 28;
        if(e.getSource() == btn29)
            seat = 29;
        if(e.getSource() == btn30)
            seat = 30;
//        JOptionPane.showMessageDialog(this, seat);
    }

    @Override
    public void mousePressed(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseReleased(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseEntered(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseExited(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
